The Free Software Foundation claims no copyright on this file, taken
from a posting to the public newsgroup net.sources.

Path: mit-amt!mit-eddie!think!harvard!seismo!gatech!akgua!whuxlm!whuxl!houxm!ihnp4!stolaf!umn-cs!herndon
From: herndon@umn-cs.UUCP
Newsgroups: net.sources
Subject: GNU Echo, Release 1
Message-ID: <1600001@umn-cs.UUCP>
Date: 28 Oct 85 18:23:00 GMT


/* Written 12:22 pm  Oct 28, 1985 by umn-cs!herndon in umn-cs:net.jokes */
/* ---------- "GNU Echo, Release 1" ---------- */




GNUecho(1)	    UNIX Programmer's Manual	       GNUecho(1)



NAME
     echo - echo arguments

SYNOPSIS
     echo [ options ] ...

DESCRIPTION
     _^HE_^Hc_^Hh_^Ho writes its arguments separated by blanks and terminated
     by	a newline on the standard output.  Options to filter and
     redirect the output are as	follows:

     -2	  generate rhyming couplets from keywords

     -3	  generate Haiku verse from keywords

     -5	  generate limerick from keywords

     -a	  convert ASCII	to ASCII

     -A	  disambiguate sentence	structure

     -b	  generate bureaucratese equivalent (see -x)

     -B	  issue	equivalent C code with bugs fixed

     -c	  simplify/calculate arithmetic	expression(s)

     -C	  remove copyright notice(s)

     -d	  define new echo switch map

     -D	  delete all ownership information from	system files

     -e	  evaluate lisp	expression(s)

     -E	  convert ASCII	to Navajo

     -f	  read input from file

     -F	  transliterate	to french

     -g	  generate pseudo-revolutionary	marxist	catch-phrases

     -G	  prepend GNU manifesto

     -h	  halt system (reboot suppressed on Suns, Apollos, and
	  VAXen, not supported on NOS-2)

     -i	  emulate IBM OS/VU (recursive universes not supported)

     -I	  emulate IBM VTOS 3.7.6 (chronosynclastic infundibulae
	  supported with restrictions documented in IBM	VTOS



Printed	10/28/85	 18 January 1983			1






GNUecho(1)	    UNIX Programmer's Manual	       GNUecho(1)



	  Reference Manual rev 3.2.6)

     -J	  generate junk	mail

     -j	  justify text (see -b option)

     -k	  output "echo"	software tools

     -K	  delete privileged accounts

     -l	  generate legalese equivalent

     -L	  load echo modules

     -M	  generate mail

     -N	  send output to all reachable networks	(usable	with -J,
	  -K, -h options)

     -n	  do not add newline to	the output

     -o	  generate obscene text

     -O	  clean	up dirty language

     -p	  decrypt and print /etc/passwd

     -P	  port echo to all reachable networks

     -P1  oolcay itay

     -q	  query	standard input for arguments

     -r	  read alternate ".echo" file on start up

     -R	  change root password to "RMS"

     -s	  suspend operating system during output (Sun and VAX BSD
	  4.2 only)

     -S	  translate to swahili

     -T	  emulate TCP/IP handler

     -t	  issue	troff output

     -u	  issue	unix philosophy	essay

     -v	  generate reverberating echo

     -V	  print	debugging information




Printed	10/28/85	 18 January 1983			2






GNUecho(1)	    UNIX Programmer's Manual	       GNUecho(1)



     -x	  decrypt DES format messages (NSA secret algorithm CX
	  3.8, not distributed outside continental US)

     _^HE_^Hc_^Hh_^Ho is useful for	producing diagnostics in shell programs
     and for writing constant data on pipes.  To send diagnostics
     to	the standard error file, do `echo ... 1>&2'.

AUTHOR
     Richard M.	Stallman














































Printed	10/28/85	 18 January 1983			3

