;;; cus-load.el --- automatically extracted custom dependencies
;;
;;; Code:

(put 'avoid 'custom-loads '(avoid))
(put 'crisp 'custom-loads '(crisp))
(put 'perl 'custom-loads '(perl-mode))
(put 'emerge 'custom-loads '(emerge))
(put 'sh-script 'custom-loads '(sh-script))
(put 'keyboard 'custom-loads '(chistory keypad kmacro type-break))
(put 'tildify 'custom-loads '(tildify))
(put 'org-protocol 'custom-loads '(org-protocol))
(put 'org-export-tables 'custom-loads '(org-exp org-html))
(put 'spam-crm114 'custom-loads '(spam))
(put 'erc-services 'custom-loads '(erc-services))
(put 'vhdl-project 'custom-loads '(vhdl-mode))
(put 'unix 'custom-loads '(proced rlogin shell))
(put 'multimedia 'custom-loads '(doc-view image-dired mm-decode mpc thumbs))
(put 'woman-formatting 'custom-loads '(woman))
(put 'org-export-latex 'custom-loads '(org-beamer org-latex org org-exp))
(put 'eudc-ph 'custom-loads '(eudc-vars))
(put 'proced 'custom-loads '(proced))
(put 'vc-git 'custom-loads '(vc-git))
(put 'table 'custom-loads '(table))
(put 'rst-faces-defaults 'custom-loads '(rst))
(put 'gnus-summary 'custom-loads '(gnus-sum gnus))
(put 'spam-stat 'custom-loads '(spam-stat))
(put 'comint-completion 'custom-loads '(comint))
(put 'pcmpl-cvs 'custom-loads '(pcmpl-cvs))
(put 'SQL 'custom-loads '(sql))
(put 'ruby 'custom-loads '(ruby-mode))
(put 'custom-magic-faces 'custom-loads '(cus-edit))
(put 'erc-fill 'custom-loads '(erc-fill))
(put 'nroff 'custom-loads '(nroff-mode))
(put 'gnus-summary-choose 'custom-loads '(gnus-sum))
(put 'pcmpl-unix 'custom-loads '(pcmpl-unix))
(put 'org-link-store 'custom-loads '(org org-gnus))
(put 'archive 'custom-loads '(arc-mode))
(put 'org-agenda-skip 'custom-loads '(org-agenda org))
(put 'gnus-cache 'custom-loads '(gnus-cache gnus))
(put 'semantic-symref 'custom-loads '("list"))
(put 'gnus-extract-archive 'custom-loads '(gnus-uu))
(put 'cperl-autoinsert-details 'custom-loads '(cperl-mode))
(put 'ielm 'custom-loads '(ielm))
(put 'debug 'custom-loads '(debug))
(put 'reftex-finding-files 'custom-loads '(reftex-vars))
(put 'erc-ibuffer 'custom-loads '(erc-ibuffer))
(put 'hideshow 'custom-loads '(hideshow))
(put 'gnus-demon 'custom-loads '(gnus-demon))
(put 'imenu 'custom-loads '(imenu "imenu"))
(put 'eshell-hist 'custom-loads '(em-hist))
(put 'ps-print-headers 'custom-loads '(ps-print))
(put 'debugger 'custom-loads '(debug))
(put 'latin1-display 'custom-loads '(latin1-disp))
(put 'eshell-util 'custom-loads '(esh-util))
(put 'doc-view 'custom-loads '(doc-view))
(put 'password 'custom-loads '(password-cache))
(put 'rmail-reply 'custom-loads '(rmail))
(put 'eshell-alias 'custom-loads '(em-alias))
(put 'artist-text 'custom-loads '(artist))
(put 'spam-report 'custom-loads '(spam-report))
(put 'nnmail-duplicate 'custom-loads '(nnmail))
(put 'message-mail 'custom-loads '(message))
(put 'prolog-indentation 'custom-loads '(prolog))
(put 'uce 'custom-loads '(uce))
(put 'games 'custom-loads '(5x5 bruce bubbles decipher dunnet fortune gametree gomoku handwrite hanoi landmark mpuz pong solitaire spook tetris yow))
(put 'org-babel 'custom-loads '(ob-js ob-lisp org ob-lob ob-maxima ob ob-picolisp ob-tangle ob-scheme ob-sh org-exp-blocks ob-exp ob-plantuml org-src))
(put 'eshell-unix 'custom-loads '(em-unix))
(put 'bubbles 'custom-loads '(bubbles))
(put 'gnus-group-visual 'custom-loads '(gnus-group gnus))
(put 'widget-browse 'custom-loads '(wid-browse))
(put 'org-appearance 'custom-loads '(org-faces org))
(put 'woman-faces 'custom-loads '(woman))
(put 'gnus-article-hiding 'custom-loads '(gnus-cite gnus-art gnus-sum))
(put 'whitespace 'custom-loads '(whitespace))
(put 'tree-widget 'custom-loads '(tree-widget))
(put 'srecode 'custom-loads '("document" "cpp" "expandproto" "fields" "insert" "map" "mode" "srt-mode"))
(put 'allout-developer 'custom-loads '(allout))
(put 'org-properties 'custom-loads '(org))
(put 'reftex-defining-label-environments 'custom-loads '(reftex-vars))
(put 'ido 'custom-loads '(ido))
(put 'ecomplete 'custom-loads '(ecomplete))
(put 'tpu 'custom-loads '("tpu-extras" tpu-edt))
(put 'f90 'custom-loads '(f90))
(put 'org-bbdb-anniversaries 'custom-loads '(org-bbdb))
(put 'nnmail-procmail 'custom-loads '(nnmail))
(put 'uniquify 'custom-loads '(uniquify))
(put 'reftex-making-and-inserting-labels 'custom-loads '(reftex-vars))
(put 'tramp 'custom-loads '(tramp tramp-gvfs tramp-sh tramp-cache tramp-smb))
(put 'cperl-help-system 'custom-loads '(cperl-mode))
(put 'calendar-chinese 'custom-loads '(cal-china))
(put 'abbrev 'custom-loads '(dabbrev expand hippie-exp quickurl))
(put 'sieve 'custom-loads '(sieve-mode sieve))
(put 'calendar-tex 'custom-loads '(cal-tex))
(put 'mode-line 'custom-loads '(time))
(put 'rcirc 'custom-loads '(rcirc))
(put 'erc-buffers 'custom-loads '(erc))
(put 'erc-quit-and-part 'custom-loads '(erc))
(put 'f90-indent 'custom-loads '(f90))
(put 'gnus-group-select 'custom-loads '(gnus-sum gnus gnus-group))
(put 'ps-print-horizontal 'custom-loads '(ps-print))
(put 'gnus-start-server 'custom-loads '(gnus-start))
(put 'gomoku 'custom-loads '(gomoku))
(put 'org-agenda-match-view 'custom-loads '(org-agenda))
(put 'programming 'custom-loads '(cus-edit))
(put 'gnus-agent 'custom-loads '(gnus gnus-agent))
(put 'org-agenda 'custom-loads '(org-agenda org))
(put 'eshell-ext 'custom-loads '(esh-ext))
(put 'gnus-summary-tree 'custom-loads '(gnus-salt))
(put 'supercite-hooks 'custom-loads '(supercite))
(put 'cperl 'custom-loads '(cperl-mode))
(put 'semantic 'custom-loads '("mru-bookmark" "mode" "c" semantic "edit" "grammar" "util-modes" "idle" "imenu" "lex" "lex-spp" "grep" "list" "db" "senator" "wisent"))
(put 'relax-ng 'custom-loads '(rng-valid rng-nxml rng-loc))
(put 'hashcash 'custom-loads '(hashcash))
(put 'ld-script 'custom-loads '(ld-script))
(put 'cust-print 'custom-loads '(cust-print))
(put 'rst-adjust 'custom-loads '(rst))
(put 'ffap 'custom-loads '(ffap))
(put 'tmm 'custom-loads '(tmm))
(put 'ps-print-color 'custom-loads '(ps-print))
(put 'reftex-citation-support 'custom-loads '(reftex-vars))
(put 'nnmail-split 'custom-loads '(nndiary nnmail))
(put 'browse-url 'custom-loads '(browse-url))
(put 'vc-arch 'custom-loads '(vc-arch))
(put 'tls 'custom-loads '(tls))
(put 'ediff-highlighting 'custom-loads '(ediff-init))
(put 'faces 'custom-loads '(cus-edit cwarn dired gnus hi-lock hilit-chg message paren proced ps-print rcirc rst speedbar wid-edit woman))
(put 'ls-lisp 'custom-loads '(ls-lisp))
(put 'org-export-odt 'custom-loads '(org-odt))
(put 'cfengine 'custom-loads '(cfengine))
(put 'align 'custom-loads '(align))
(put 'nnmail 'custom-loads '(nnmail))
(put 'ps-print 'custom-loads '(ps-print))
(put 'supercite-attr 'custom-loads '(supercite))
(put 'eudc-ldap 'custom-loads '(eudc-vars))
(put 'org-mac-flagged-mail 'custom-loads '(org-mac-message))
(put 'dframe 'custom-loads '(dframe))
(put 'viper-highlighting 'custom-loads '(viper-init))
(put 'lisp 'custom-loads '(advice bytecomp checkdoc cust-print edebug eldoc elp ert find-func gmm-utils ielm inf-lisp "cl-indent" shadow pp re-builder unsafep scheme testcover trace warnings xscheme))
(put 'customize 'custom-loads '(cus-edit wid-edit))
(put 'idlwave-misc 'custom-loads '(idlwave))
(put 'message-various 'custom-loads '(message))
(put 'jka-compr 'custom-loads '(jka-compr))
(put 'filesets 'custom-loads '(filesets))
(put 'term 'custom-loads '(terminal term))
(put 'emulations 'custom-loads '(crisp cua-base edt tpu-edt vip viper))
(put 'erc-replace 'custom-loads '(erc-replace))
(put 'erc-control-characters 'custom-loads '(erc-goodies))
(put 'org-link 'custom-loads '(org org-ctags org-mac-message org-mew org-wl))
(put 'printing 'custom-loads '(printing))
(put 'nndiary 'custom-loads '(nndiary))
(put 'org-export-ascii 'custom-loads '(org-ascii))
(put 'eshell-script 'custom-loads '(em-script))
(put 'lazy-highlight 'custom-loads '(ispell))
(put 'sort 'custom-loads '(sort))
(put 'org-agenda-todo-list 'custom-loads '(org-agenda))
(put 'menu 'custom-loads '(cus-edit tmm))
(put 'octave 'custom-loads '(octave-mod octave-inf))
(put 'enriched 'custom-loads '(enriched))
(put 'gnus-score-files 'custom-loads '(gnus-score gnus))
(put 'midnight 'custom-loads '(midnight))
(put 'org-lparse 'custom-loads '(org-lparse))
(put 'linum 'custom-loads '(linum))
(put 'vhdl-highlight-faces 'custom-loads '(vhdl-mode))
(put 'bibtex 'custom-loads '(bibtex bibtex-style))
(put 'gnus-summary-sort 'custom-loads '(gnus-sum))
(put 'allout-widgets-developer 'custom-loads '(allout-widgets))
(put 'spam 'custom-loads '(spam))
(put 'ebnf-displacement 'custom-loads '(ebnf2ps))
(put 'semanticdb 'custom-loads '("db-file" "db-ebrowse" "db"))
(put 'isearchb 'custom-loads '(isearchb))
(put 'view 'custom-loads '(calendar view))
(put 'ldap 'custom-loads '(ldap))
(put 'data 'custom-loads '(arc-mode conf-mode dns-mode doc-view epg-config forms generic-x hexl remember saveplace snmp-mode sort tar-mode time-stamp timeclock))
(put 'woman 'custom-loads '(woman))
(put 'org-table-calculation 'custom-loads '(org-table))
(put 'message-insertion 'custom-loads '(message))
(put 'gnus-diary 'custom-loads '(gnus-diary nndiary))
(put 'tex 'custom-loads '(bibtex tex-mode reftex-vars))
(put 'trace 'custom-loads '(trace))
(put 'widget-faces 'custom-loads '(wid-edit))
(put 'feedmail-headers 'custom-loads '(feedmail))
(put 'idlwave-online-help 'custom-loads '(idlw-help))
(put 'ebnf-except 'custom-loads '(ebnf2ps))
(put 'org-capture 'custom-loads '(org-capture))
(put 'data-debug 'custom-loads '(data-debug))
(put 'org-export-htmlize 'custom-loads '(org-html))
(put 'gnus-sync 'custom-loads '(gnus-sync))
(put 'org-feed 'custom-loads '(org-feed))
(put 'ogonek 'custom-loads '(ogonek))
(put 'document 'custom-loads '("document"))
(put 'gravatar 'custom-loads '(gravatar))
(put 'development 'custom-loads '(cus-edit))
(put 'ansi-colors 'custom-loads '(ansi-color))
(put 'eshell-term 'custom-loads '(em-term))
(put 'postscript 'custom-loads '(ebnf2ps printing ps-print))
(put 'timeclock 'custom-loads '(timeclock))
(put 'windmove 'custom-loads '(windmove))
(put 'environment 'custom-loads '(dired cus-edit "dos-vars" w32-vars))
(put 'vc-rcs 'custom-loads '(vc-rcs))
(put 'bib 'custom-loads '(bib-mode))
(put 'mail-extr 'custom-loads '(mail-extr))
(put 'cperl-faces 'custom-loads '(cperl-mode))
(put 'gnus-summary-various 'custom-loads '(gnus-sum))
(put 'gnus-extract-view 'custom-loads '(gnus-sum gnus-uu))
(put 'gnus-cite 'custom-loads '(gnus-cite gnus-msg))
(put 'idlwave-shell-general-setup 'custom-loads '(idlw-shell idlwave))
(put 'starttls 'custom-loads '(starttls))
(put 'wdired 'custom-loads '(wdired))
(put 'erc-match 'custom-loads '(erc-match))
(put 'net-utils 'custom-loads '(net-utils gnutls))
(put 'tcl 'custom-loads '(tcl))
(put 'idlwave-code-formatting 'custom-loads '(idlwave))
(put 'widgets 'custom-loads '(tree-widget wid-browse wid-edit))
(put 'mpuz 'custom-loads '(mpuz))
(put 'gnus-newsrc 'custom-loads '(gnus-start))
(put 'cedet 'custom-loads '(cedet-cscope cedet-global cedet-idutils))
(put 'emacs-lock 'custom-loads '(emacs-lock))
(put 'url-history 'custom-loads '(url-history))
(put 'footnote 'custom-loads '(footnote))
(put 'ebnf-syntactic 'custom-loads '(ebnf2ps))
(put 'follow 'custom-loads '(follow))
(put 'external 'custom-loads '(bib-mode browse-url locate man ebnf2ps cus-edit server))
(put 'tar 'custom-loads '(tar-mode))
(put 'ps-print-background 'custom-loads '(ps-print))
(put 'gud 'custom-loads '(gdb-mi gud))
(put 'yow 'custom-loads '(yow))
(put 'ispell 'custom-loads '(flyspell ispell))
(put 'ebnf-optimization 'custom-loads '(ebnf2ps))
(put 'message-interface 'custom-loads '(message))
(put 'msb 'custom-loads '(msb))
(put 'quickurl 'custom-loads '(quickurl))
(put 'tex-file 'custom-loads '(tex-mode))
(put 'nxml 'custom-loads '(nxml-mode nxml-outln rng-valid))
(put 'vhdl-style 'custom-loads '(vhdl-mode))
(put 'file-cache 'custom-loads '(filecache))
(put 'rcirc-faces 'custom-loads '(rcirc))
(put 'reftex-viewing-cross-references 'custom-loads '(reftex-vars))
(put 'pcl-cvs 'custom-loads '(pcvs-defs pcvs-info pcvs pcvs-parse cvs-status log-edit log-view))
(put 'tempo 'custom-loads '(tempo))
(put 'elide-head 'custom-loads '(elide-head))
(put 'image-dired 'custom-loads '(image-dired))
(put 'eudc 'custom-loads '(eudc-vars))
(put 'gnus-outlook-deuglify 'custom-loads '(deuglify))
(put 'w32 'custom-loads '(w32-vars))
(put 'rmail-output 'custom-loads '(rmailout))
(put 'socks 'custom-loads '(socks))
(put 'scheme 'custom-loads '(cmuscheme scheme))
(put 'editing 'custom-loads '(cus-edit electric))
(put 'apropos 'custom-loads '(apropos))
(put 'viper-hooks 'custom-loads '(viper-init))
(put 'dunnet 'custom-loads '(dunnet))
(put 'asm 'custom-loads '(asm-mode))
(put 'mail-abbrev 'custom-loads '(mailabbrev))
(put 'org-entities 'custom-loads '(org-entities))
(put 'rmail-retrieve 'custom-loads '(rmail))
(put 'org-latex 'custom-loads '(org))
(put 'erc-paranoia 'custom-loads '(erc))
(put 'viper 'custom-loads '(viper-init viper-ex viper viper-mous viper-keym viper-macs viper-util))
(put 'erc-ignore 'custom-loads '(erc))
(put 'mpc 'custom-loads '(mpc))
(put 'recentf 'custom-loads '(recentf))
(put 'gnus-group 'custom-loads '(gnus gnus-group gnus-topic))
(put 'info-lookup 'custom-loads '(info-look))
(put 'org-table 'custom-loads '(org org-table))
(put 'gdb-non-stop 'custom-loads '(gdb-mi))
(put 'vhdl-highlight 'custom-loads '(vhdl-mode))
(put 'holidays 'custom-loads '(calendar holidays))
(put 'org-table-editing 'custom-loads '(org-table org))
(put 'newsticker-plainview 'custom-loads '(newst-plainview))
(put 'delphi 'custom-loads '(delphi))
(put 'matching 'custom-loads '(bookmark completion ffap imenu))
(put 'allout-encryption 'custom-loads '(allout))
(put 'netrc 'custom-loads '(netrc))
(put 'mime-security 'custom-loads '(gnus-art mm-decode mm-encode mml-smime mml2015))
(put 'eshell-glob 'custom-loads '(em-glob))
(put 'speedbar 'custom-loads '("sb" speedbar sb-image))
(put 'refer 'custom-loads '(refer))
(put 'terminal 'custom-loads '(terminal))
(put 'etags 'custom-loads '(etags speedbar))
(put 'allout-widgets 'custom-loads '(allout-widgets))
(put 'newsticker-plainview-hooks 'custom-loads '(newst-plainview))
(put 'viper-mouse 'custom-loads '(viper-mous))
(put 'dos-fns 'custom-loads '("dos-vars"))
(put 'gmm 'custom-loads '(gmm-utils))
(put 'gnus-extract-post 'custom-loads '(gnus-uu))
(put 'message-headers 'custom-loads '(message))
(put 'font-lock 'custom-loads '(hi-lock prolog))
(put 'gnus-score-decay 'custom-loads '(gnus-score))
(put 'rst-toc 'custom-loads '(rst))
(put 'org-ctags 'custom-loads '(org-ctags))
(put 'grep 'custom-loads '(grep))
(put 'ediff-mult 'custom-loads '(ediff-mult))
(put 're-builder 'custom-loads '(re-builder))
(put 'org-progress 'custom-loads '(org-clock org org-habit))
(put 'ps-print-zebra 'custom-loads '(ps-print))
(put 'emacs 'custom-loads '(cus-edit ebnf2ps))
(put 'erc-page 'custom-loads '(erc-page))
(put 'gnus-score-adapt 'custom-loads '(gnus-score gnus))
(put 'shr 'custom-loads '(shr shr-color))
(put 'chistory 'custom-loads '(chistory))
(put 'url-cookie 'custom-loads '(url-cookie))
(put 'icon 'custom-loads '(icon))
(put 'metamail 'custom-loads '(metamail))
(put 'gnus-score-kill 'custom-loads '(gnus gnus-kill))
(put 'convenience 'custom-loads '(cus-edit autoinsert autorevert bs completion cua-base dabbrev emacs-lock ffap filecache filesets follow hippie-exp hl-line ibuffer ido imenu iswitchb kmacro linum master org-protocol repeat reveal ruler-mode speedbar vcursor whitespace windmove))
(put 'wisent 'custom-loads '("wisent" "comp"))
(put 'ediff 'custom-loads '(ediff-init ediff-diff ediff-mult ediff-ptch ediff ediff-wind))
(put 'org-priorities 'custom-loads '(org))
(put 'org-export-general 'custom-loads '(org-exp org-exp-blocks))
(put 'pong 'custom-loads '(pong))
(put 'gnus-message 'custom-loads '(gnus-msg gnus-draft gnus message))
(put 'ps-print-font 'custom-loads '(ps-print ps-mule))
(put 'erc-scripts 'custom-loads '(erc))
(put 'gnus-delay 'custom-loads '(gnus-delay))
(put 'erc-notify 'custom-loads '(erc-notify))
(put 'verilog-mode-auto 'custom-loads '(verilog-mode))
(put 'feedmail-misc 'custom-loads '(feedmail))
(put 'rmail-edit 'custom-loads '(rmailedit))
(put 'gametree 'custom-loads '(gametree))
(put 'hardware 'custom-loads '(battery))
(put 'news 'custom-loads '(binhex canlock gnus message mm-decode spam spam-report supercite uudecode))
(put 'pop3 'custom-loads '(pop3))
(put 'org-freemind 'custom-loads '(org-freemind))
(put 'gnus-exit 'custom-loads '(gnus-group gnus))
(put 'erc-speedbar 'custom-loads '(erc-speedbar))
(put 'verilog-mode 'custom-loads '(verilog-mode))
(put 'org-agenda-daily/weekly 'custom-loads '(org-agenda org-faces org))
(put 'erc-truncate 'custom-loads '(erc-truncate))
(put 'ses 'custom-loads '(ses))
(put 'eshell-banner 'custom-loads '(em-banner))
(put 'vhdl 'custom-loads '(vhdl-mode))
(put 'LaTeX 'custom-loads '(reftex-vars))
(put 'mouse-sel 'custom-loads '(mouse-sel))
(put 'picture 'custom-loads '(picture))
(put 'gnus-article-emphasis 'custom-loads '(gnus-art))
(put 'mouse 'custom-loads '(artist avoid goto-addr cus-edit mouse-sel msb strokes))
(put 'prolog 'custom-loads '(prolog))
(put 'bookmark 'custom-loads '(man bookmark))
(put 'icalendar 'custom-loads '(icalendar))
(put 'lisp-shadow 'custom-loads '(shadow))
(put 'diary 'custom-loads '(calendar diary-lib cal-hebrew))
(put 'cperl-speed 'custom-loads '(cperl-mode))
(put 'viper-search 'custom-loads '(viper-init))
(put 'nnmairix 'custom-loads '(nnmairix))
(put 'extensions 'custom-loads '(cust-print data-debug ede eldoc ido page-ext srecode time-stamp wid-edit xesam))
(put 'nnmail-retrieve 'custom-loads '(nnmail))
(put 'save-place 'custom-loads '(saveplace))
(put 'rst 'custom-loads '(rst))
(put 'org-cycle 'custom-loads '(org))
(put 'remote-compile 'custom-loads '(rcompile))
(put 'BibTeX 'custom-loads '(bibtex))
(put 'snmp 'custom-loads '(snmp-mode))
(put 'org-faces 'custom-loads '(org-faces org org-footnote org-habit))
(put 'supercite 'custom-loads '(supercite))
(put 'newsticker-faces 'custom-loads '(newst-plainview newst-reader))
(put 'i18n 'custom-loads '(ccl double iso-ascii latin1-disp cus-edit ogonek url-vars))
(put 'org-export-html 'custom-loads '(org-agenda org-html org-exp org-jsinfo))
(put 'vhdl-comment 'custom-loads '(vhdl-mode))
(put 'internal 'custom-loads '(cus-edit))
(put 'outlines 'custom-loads '(allout org outline))
(put 'vhdl-align 'custom-loads '(vhdl-mode))
(put 'maint 'custom-loads '(elint emacsbug gulp lisp-mnt))
(put 'nnmail-various 'custom-loads '(nnmail))
(put 'reftex-label-support 'custom-loads '(reftex-vars))
(put 'eldoc 'custom-loads '(eldoc))
(put 'reftex-referencing-labels 'custom-loads '(reftex-vars))
(put 'hanoi 'custom-loads '(hanoi))
(put 'reftex-index-support 'custom-loads '(reftex-vars))
(put 'prolog-inferior 'custom-loads '(prolog))
(put 'modula2 'custom-loads '(modula2))
(put 'gdb 'custom-loads '(gdb-mi))
(put 'gnus-picon 'custom-loads '(gnus-art gnus-picon))
(put 'url-gateway 'custom-loads '(url-gw))
(put 'which-func 'custom-loads '(which-func))
(put 'rmail 'custom-loads '(rmail rmailmm rmail-spam-filter))
(put 'man 'custom-loads '(man))
(put 'strokes 'custom-loads '(strokes))
(put 'pcmpl-gnu 'custom-loads '(pcmpl-gnu))
(put 'completion 'custom-loads '(completion iswitchb))
(put 'org-babel-tangle 'custom-loads '(ob-tangle))
(put 'eshell-module 'custom-loads '(esh-module))
(put 'eieio 'custom-loads '(chart eieio-custom))
(put 'PostScript 'custom-loads '(ps-mode))
(put 'rmail-files 'custom-loads '(rmail))
(put 'reftex 'custom-loads '(reftex-vars))
(put 'lpr 'custom-loads '(lpr))
(put 'ada 'custom-loads '(ada-xref ada-mode))
(put 'hippie-expand 'custom-loads '(hippie-exp))
(put 'hi-lock 'custom-loads '(hi-lock))
(put 'viper-misc 'custom-loads '(viper viper-init viper-cmd))
(put 'gnus-group-new 'custom-loads '(gnus-start))
(put 'gnus-thread 'custom-loads '(gnus-sum gnus-group))
(put 'time-stamp 'custom-loads '(time-stamp))
(put 'paren-matching 'custom-loads '(paren))
(put 'vhdl-template 'custom-loads '(vhdl-mode))
(put 'soap-client 'custom-loads '(soap-client))
(put 'dns-mode 'custom-loads '(dns-mode))
(put 'checkdoc 'custom-loads '(checkdoc))
(put 'org-agenda-line-format 'custom-loads '(org-agenda))
(put 'refbib 'custom-loads '(refbib))
(put 'hl-line 'custom-loads '(hl-line))
(put 'gnus-article-buttons 'custom-loads '(gnus-art))
(put 'eshell-var 'custom-loads '(esh-var))
(put 'archive-zoo 'custom-loads '(arc-mode))
(put 'ediff-ptch 'custom-loads '(ediff-ptch))
(put 'calendar-html 'custom-loads '(cal-html))
(put 'gnus-article-various 'custom-loads '(gnus-art gnus-sum))
(put 'uudecode 'custom-loads '(uudecode))
(put 'vhdl-print 'custom-loads '(vhdl-mode))
(put 'winner 'custom-loads '(winner))
(put 'iswitchb 'custom-loads '(isearchb iswitchb))
(put 'erc-dcc 'custom-loads '(erc-dcc erc-xdcc))
(put 'lisp-indent 'custom-loads '("cl-indent"))
(put 'basic-faces 'custom-loads '(cus-edit shadowfile))
(put 'org-mobile 'custom-loads '(org-mobile))
(put 'change-log 'custom-loads '(add-log))
(put 'processes 'custom-loads '(sql ansi-color comint compile executable cus-edit flyspell grep gud metamail pcomplete proced rcompile rlogin shell socks term))
(put 'table-hooks 'custom-loads '(table))
(put 'sieve-manage 'custom-loads '(sieve-manage))
(put 'mm-url 'custom-loads '(mm-url))
(put 'org-export-docbook 'custom-loads '(org-docbook))
(put 'custom-browse 'custom-loads '(cus-edit))
(put 'desktop 'custom-loads '(desktop))
(put 'mode-line-faces 'custom-loads '(time cus-edit))
(put 'org-bibtex 'custom-loads '(org-bibtex))
(put 'ange-ftp 'custom-loads '(ange-ftp))
(put 'spook 'custom-loads '(spook))
(put 'mule 'custom-loads '(descr-text kkc latexenc))
(put 'org-time 'custom-loads '(org org-timer))
(put 'kmacro 'custom-loads '(edmacro kmacro))
(put 'gnus-summary-pick 'custom-loads '(gnus-salt))
(put 'fill 'custom-loads '(align newcomment longlines refill))
(put 'org-agenda-time-grid 'custom-loads '(org-agenda))
(put 'ebnf-special 'custom-loads '(ebnf2ps))
(put 'proced-faces 'custom-loads '(proced))
(put 'flyspell 'custom-loads '(flyspell))
(put 'double 'custom-loads '(double))
(put 'dabbrev 'custom-loads '(dabbrev))
(put 'octave-inferior 'custom-loads '(octave-mod octave-inf))
(put 'erc-server 'custom-loads '(erc-backend))
(put 'font-lock-highlighting-faces 'custom-loads '(vera-mode verilog-mode))
(put 'gnus-article-signature 'custom-loads '(gnus-art))
(put 'paren-showing-faces 'custom-loads '(paren))
(put 'calendar-faces 'custom-loads '(calendar diary-lib))
(put 'mime 'custom-loads '(mailcap mm-bodies mm-util mm-encode rfc1843 smime))
(put 'gnus-score 'custom-loads '(gnus))
(put 'org-inlinetask 'custom-loads '(org-inlinetask))
(put 'bruce 'custom-loads '(bruce))
(put 'message-news 'custom-loads '(message))
(put 'shadow 'custom-loads '(shadowfile))
(put 'gnus-server-visual 'custom-loads '(gnus-srvr))
(put 'gnus-article-treat 'custom-loads '(gnus-art))
(put 'ezimage 'custom-loads '(ezimage))
(put 'semantic-imenu 'custom-loads '("imenu"))
(put 'pulse 'custom-loads '(pulse))
(put 'savehist 'custom-loads '(savehist))
(put 'gnus-article-washing 'custom-loads '(gnus-art))
(put 'org-footnote 'custom-loads '(org-footnote))
(put 'erc-netsplit 'custom-loads '(erc-netsplit))
(put 'org-export-taskjuggler 'custom-loads '(org-taskjuggler))
(put 'widget-documentation 'custom-loads '(wid-edit))
(put 'archive-zip 'custom-loads '(arc-mode))
(put 'vhdl-compose 'custom-loads '(vhdl-mode))
(put 'gnus-topic 'custom-loads '(gnus-topic))
(put 'smerge 'custom-loads '(smerge-mode))
(put 'gnus-extract 'custom-loads '(gnus-uu gnus))
(put 'tooltip 'custom-loads '(gud))
(put 'sh-indentation 'custom-loads '(sh-script))
(put 'ps-print-vertical 'custom-loads '(ps-print))
(put 'reftex-fontification-configurations 'custom-loads '(reftex-vars))
(put 'pascal 'custom-loads '(pascal))
(put 'network 'custom-loads '(gssapi))
(put 'gnus-score-various 'custom-loads '(gnus-score gnus))
(put 'ruler-mode 'custom-loads '(ruler-mode))
(put 'erc-pcomplete 'custom-loads '(erc-pcomplete))
(put 'gnus-asynchronous 'custom-loads '(gnus-async))
(put 'plstore 'custom-loads '(plstore))
(put 'org-refile 'custom-loads '(org))
(put 'forms 'custom-loads '(forms))
(put 'org-structure 'custom-loads '(org org-inlinetask org-list))
(put 'vc-cvs 'custom-loads '(vc-cvs))
(put 'auto-revert 'custom-loads '(autorevert))
(put 'nxml-faces 'custom-loads '(nxml-mode nxml-outln))
(put 'vhdl-menu 'custom-loads '(vhdl-mode))
(put 'pcomplete 'custom-loads '(em-cmpl pcmpl-cvs pcmpl-gnu pcmpl-linux pcomplete))
(put 'fortran 'custom-loads '(fortran))
(put 'ebnf-non-terminal 'custom-loads '(ebnf2ps))
(put 'org-todo 'custom-loads '(org org-clock org-faces))
(put 'org-mew 'custom-loads '(org-mew))
(put 'org-bbdb 'custom-loads '(org-bbdb))
(put 'eudc-bbdb 'custom-loads '(eudc-vars))
(put 'elint 'custom-loads '(elint))
(put 'cmuscheme 'custom-loads '(cmuscheme))
(put 'ebnf2ps 'custom-loads '(ebnf2ps))
(put 'eshell-cmd 'custom-loads '(esh-cmd))
(put 'message-faces 'custom-loads '(message))
(put 'executable 'custom-loads '(executable))
(put 'applications 'custom-loads '(calc calculator calendar doc-view erc eshell cus-edit htmlfontify ispell mpc newst-backend package rcirc ses))
(put 'compilation 'custom-loads '(compile))
(put 'info 'custom-loads '(info))
(put 'gnus-group-foreign 'custom-loads '(gnus-group gnus-msg))
(put 'ediff-vers 'custom-loads '(ediff-vers))
(put 'sgml 'custom-loads '(sgml-mode))
(put 'nnmail-expire 'custom-loads '(nnmail))
(put 'display 'custom-loads '(face-remap))
(put 'newsticker-miscellaneous 'custom-loads '(newst-backend))
(put 'org-crypt 'custom-loads '(org-crypt))
(put 'remember 'custom-loads '(remember))
(put 'spam-bsfilter 'custom-loads '(spam))
(put 'erc-stamp 'custom-loads '(erc-stamp))
(put 'verilog-mode-actions 'custom-loads '(verilog-mode))
(put 'dired-keys 'custom-loads '(dired-x))
(put 'conf 'custom-loads '(conf-mode))
(put 'handwrite 'custom-loads '(handwrite))
(put 'srecode-cpp 'custom-loads '("cpp"))
(put 'supercite-cite 'custom-loads '(supercite))
(put 'flymake 'custom-loads '(flymake))
(put 'allout 'custom-loads '(allout allout-widgets))
(put 'gnus-server 'custom-loads '(gnus-srvr gnus gnus-int nnheader))
(put 'feedmail-debug 'custom-loads '(feedmail))
(put 'comm 'custom-loads '(ange-ftp browse-url dig eudc-vars goto-addr gravatar ldap net-utils netrc tls tramp url-vars xesam))
(put 'gnus-threading 'custom-loads '(gnus-sum))
(put 'rlogin 'custom-loads '(rlogin))
(put 'ert 'custom-loads '(ert))
(put 'url-file 'custom-loads '(url-cache url-cookie url-vars))
(put 'semantic-faces 'custom-loads '("complete" "include" "mode" "util-modes" "senator" "fields"))
(put 'newsticker-hooks 'custom-loads '(newst-backend newst-plainview))
(put 'reftex-optimizations-for-large-documents 'custom-loads '(reftex-vars))
(put 'message-sending 'custom-loads '(message))
(put 'todo 'custom-loads '(todo-mode))
(put 'idlwave-abbrev-and-indent-action 'custom-loads '(idlwave))
(put 'PostScript-interaction 'custom-loads '(ps-mode))
(put 'mailalias 'custom-loads '(mailalias))
(put 'smie 'custom-loads '(smie))
(put 'bs-appearance 'custom-loads '(bs))
(put 'org-agenda-export 'custom-loads '(org-agenda))
(put 'server 'custom-loads '(server))
(put 'emacsbug 'custom-loads '(emacsbug))
(put 'erc 'custom-loads '(erc-autoaway erc-join erc erc-button erc-capab erc-goodies erc-dcc erc-ezbounce erc-fill erc-ibuffer erc-identd erc-log erc-match erc-netsplit erc-networks erc-notify erc-page erc-pcomplete erc-replace erc-services erc-sound erc-speedbar erc-stamp erc-track erc-truncate))
(put 'org-wl 'custom-loads '(org-wl))
(put 'url-mime 'custom-loads '(url-vars))
(put 'comment 'custom-loads '(newcomment))
(put 'landmark 'custom-loads '(landmark))
(put 'gnus-windows 'custom-loads '(gnus-win))
(put 'hexl 'custom-loads '(hexl))
(put 'vhdl-header 'custom-loads '(vhdl-mode))
(put 'vhdl-compile 'custom-loads '(vhdl-mode))
(put 'gnus-group-levels 'custom-loads '(gnus-start gnus gnus-group))
(put 'help-at-pt 'custom-loads '(help-at-pt))
(put 'org-imenu-and-speedbar 'custom-loads '(org))
(put 'smtpmail 'custom-loads '(smtpmail))
(put 'epg 'custom-loads '(epa epg-config))
(put 'gnus-gravatar 'custom-loads '(gnus-gravatar))
(put 'vhdl-sequential-process 'custom-loads '(vhdl-mode))
(put 'gnus-art 'custom-loads '(gnus-art gnus-html))
(put 'epa 'custom-loads '(epa))
(put 'mail-hist 'custom-loads '(mail-hist))
(put 'message 'custom-loads '(footnote message mml mml-sec))
(put 'rmail-headers 'custom-loads '(rmail undigest))
(put 'gnus-article-headers 'custom-loads '(gnus-art gnus-sum gnus-fun))
(put 'abbrev-mode 'custom-loads '(mailabbrev))
(put 'recentf-filters 'custom-loads '(recentf))
(put 'eshell-mode 'custom-loads '(esh-mode))
(put 'makefile 'custom-loads '(make-mode))
(put 'org-mouse 'custom-loads '(org-mouse))
(put 'ebrowse-faces 'custom-loads '(ebrowse))
(put 'spam-bogofilter 'custom-loads '(spam))
(put 'mail-source 'custom-loads '(mail-source nndiary pop3))
(put 'ebnf-shape 'custom-loads '(ebnf2ps))
(put 'erc-capab 'custom-loads '(erc-capab))
(put 'mime-display 'custom-loads '(flow-fill mm-decode mm-view))
(put 'calendar-dst 'custom-loads '(cal-dst))
(put 'dired 'custom-loads '(dired dired-aux dired-x find-dired ls-lisp wdired))
(put 'reveal 'custom-loads '(reveal))
(put 'custom-menu 'custom-loads '(cus-edit))
(put 'nnmail-prepare 'custom-loads '(nnmail))
(put 'smime 'custom-loads '(smime))
(put 'paren-showing 'custom-loads '(paren))
(put 'wp 'custom-loads '(bib-mode delim-col ebnf2ps enriched lpr nroff-mode outline picture printing ps-print refbib refer rng-valid rst table cus-edit tildify view))
(put 'senator 'custom-loads '("senator"))
(put 'newsticker 'custom-loads '(newst-backend newst-reader newst-ticker))
(put 'elp 'custom-loads '(elp))
(put 'archive-7z 'custom-loads '(arc-mode))
(put 'vhdl-model 'custom-loads '(vhdl-mode))
(put 'gnus-article-saving 'custom-loads '(gnus gnus-art))
(put 'idlwave-shell-highlighting-and-faces 'custom-loads '(idlw-shell))
(put 'org-agenda-custom-commands 'custom-loads '(org-agenda))
(put 'gnus-various 'custom-loads '(gnus-util gnus-sum gnus))
(put 'feedmail-spray 'custom-loads '(feedmail))
(put 'ebrowse-member 'custom-loads '(ebrowse))
(put 'dired-x 'custom-loads '(dired-x))
(put 'inferior-lisp 'custom-loads '(inf-lisp))
(put 'binhex 'custom-loads '(binhex))
(put 'archive-arc 'custom-loads '(arc-mode))
(put 'vc 'custom-loads '(log-edit vc vc-annotate vc-arch vc-bzr vc-dispatcher vc-cvs vc-dir vc-git vc-hg vc-mtn vc-rcs vc-sccs vc-svn))
(put 'erc-faces 'custom-loads '(erc-goodies erc erc-button erc-capab erc-match erc-stamp))
(put 'vc-bzr 'custom-loads '(vc-bzr))
(put 'advice 'custom-loads '(advice))
(put 'calendar 'custom-loads '(appt calendar cal-x cal-china cal-dst cal-html solar cal-tex diary-lib holidays icalendar lunar midnight org todo-mode))
(put 'locate 'custom-loads '(locate))
(put 'goto-address 'custom-loads '(goto-addr))
(put 'org-clock 'custom-loads '(org-agenda org-clock))
(put 'vhdl-port 'custom-loads '(vhdl-mode))
(put 'multi-isearch 'custom-loads '("misearch"))
(put 'ebnf-repeat 'custom-loads '(ebnf2ps))
(put 'allout-keybindings 'custom-loads '(allout))
(put 'spam-spamoracle 'custom-loads '(spam))
(put 'woman-interface 'custom-loads '(woman))
(put 'gnus-summary-exit 'custom-loads '(gnus-sum gnus))
(put 'mspools 'custom-loads '(mspools))
(put 'ps-print-page 'custom-loads '(ps-print))
(put 'gnus-charset 'custom-loads '(gnus gnus-group gnus-sum))
(put 'bibtex-autokey 'custom-loads '(bibtex))
(put 'erc-button 'custom-loads '(erc-button))
(put 'htmlfontify 'custom-loads '(htmlfontify))
(put 'erc-networks 'custom-loads '(erc-networks))
(put 'artist 'custom-loads '(artist))
(put 'log-edit 'custom-loads '(log-edit))
(put 'sh 'custom-loads '(sh-script))
(put 'gnus-summary-visual 'custom-loads '(gnus-sum))
(put '5x5 'custom-loads '(5x5))
(put 'cperl-indentation-details 'custom-loads '(cperl-mode))
(put 'newsticker-headline-processing 'custom-loads '(newst-backend))
(put 'dirtrack 'custom-loads '(dirtrack))
(put 'smiley 'custom-loads '(smiley))
(put 'calendar-hooks 'custom-loads '(cal-x calendar))
(put 'ebnf-terminal 'custom-loads '(ebnf2ps))
(put 'makeinfo 'custom-loads '(makeinfo))
(put 'org-keywords 'custom-loads '(org))
(put 'pages 'custom-loads '(page-ext))
(put 'gnus-visual 'custom-loads '(gnus-art gnus-gravatar gnus smiley))
(put 'idlwave-completion 'custom-loads '(idlwave))
(put 'speedbar-faces 'custom-loads '(speedbar vhdl-mode))
(put 'ibuffer 'custom-loads '(ibuffer ibuf-ext))
(put 'generic-x 'custom-loads '(generic-x))
(put 'epa-file 'custom-loads '(epa-file))
(put 'gnus-files 'custom-loads '(gnus nnmail))
(put 'cperl-affected-by-hairy 'custom-loads '(cperl-mode))
(put 'find-dired 'custom-loads '(find-dired))
(put 'archive-lzh 'custom-loads '(arc-mode))
(put 'two-column 'custom-loads '(two-column))
(put 'ediff-merge 'custom-loads '(ediff-init ediff-merg))
(put 'org-sparse-trees 'custom-loads '(org))
(put 'speedbar-vc 'custom-loads '(speedbar))
(put 'eshell-basic 'custom-loads '(em-basic))
(put 'meta-font 'custom-loads '(meta-mode))
(put 'bytecomp 'custom-loads '(bytecomp))
(put 'pp 'custom-loads '(pp))
(put 'vera 'custom-loads '(vera-mode))
(put 'gnus-undo 'custom-loads '(gnus-undo))
(put 'shell-directories 'custom-loads '(shell))
(put 'compare-windows 'custom-loads '(compare-w))
(put 'diff-mode 'custom-loads '(diff-mode))
(put 'ps-print-miscellany 'custom-loads '(ps-bdf ps-print))
(put 'gulp 'custom-loads '(gulp))
(put 'help 'custom-loads '(apropos cus-edit ehelp help-at-pt help-fns help-mode info info-look man help-macro tutorial woman))
(put 'lisp-mnt 'custom-loads '(lisp-mnt))
(put 'type-break 'custom-loads '(type-break))
(put 'idlwave 'custom-loads '(idlwave idlw-help idlw-shell))
(put 'erc-track 'custom-loads '(erc-track))
(put 'spam-ifile 'custom-loads '(spam))
(put 'edt 'custom-loads '(edt))
(put 'eshell-ls 'custom-loads '(em-ls))
(put 'erc-spelling 'custom-loads '(erc-spelling))
(put 'erc-sound 'custom-loads '(erc-sound))
(put 'gnus-fun 'custom-loads '(gnus-fun))
(put 'auth-source 'custom-loads '(auth-source))
(put 'ede 'custom-loads '(ede "locate" "make" "base" "project-am"))
(put 'fortran-comment 'custom-loads '(fortran))
(put 'newsticker-retrieval 'custom-loads '(newst-backend))
(put 'electricity 'custom-loads '(electric))
(put 'org-id 'custom-loads '(org org-id))
(put 'ediff-window 'custom-loads '(ediff-wind ediff-help))
(put 'idlwave-documentation 'custom-loads '(idlwave))
(put 'org-export 'custom-loads '(org-ascii org-docbook org-exp org-html org-icalendar org-latex org-odt org-taskjuggler))
(put 'eshell 'custom-loads '(esh-arg eshell esh-cmd esh-ext esh-io esh-mode esh-module esh-opt esh-proc esh-util esh-var))
(put 'ps-print-n-up 'custom-loads '(ps-print))
(put 'org-habit 'custom-loads '(org-habit))
(put 'prolog-font-lock 'custom-loads '(prolog))
(put 'custom-buffer 'custom-loads '(cus-edit cus-theme))
(put 'simula 'custom-loads '(simula))
(put 'spam-spamassassin 'custom-loads '(spam))
(put 'eshell-io 'custom-loads '(esh-io))
(put 'copyright 'custom-loads '(copyright))
(put 'eshell-rebind 'custom-loads '(em-rebind))
(put 'gnus-start 'custom-loads '(gnus-int gnus-start gnus gnus-group gnus-util nnheader))
(put 'gnus-meta 'custom-loads '(gnus-util gnus))
(put 'newsticker-treeview 'custom-loads '(newst-treeview))
(put 'rmail-mime 'custom-loads '(rmailmm))
(put 'tex-run 'custom-loads '(tex-mode))
(put 'imap 'custom-loads '(imap))
(put 'antlr 'custom-loads '(antlr-mode))
(put 'gnus-duplicate 'custom-loads '(gnus-dup))
(put 'js 'custom-loads '(js))
(put 'epa-faces 'custom-loads '(epa))
(put 'fortran-indent 'custom-loads '(fortran))
(put 'org-attach 'custom-loads '(org-attach))
(put 'gnus-bookmark 'custom-loads '(gnus-bookmark))
(put 'image 'custom-loads '(iimage image-mode image-file))
(put 'm4 'custom-loads '(m4-mode))
(put 'org-completion 'custom-loads '(org))
(put 'project-am 'custom-loads '("project-am"))
(put 'cwarn 'custom-loads '(cwarn))
(put 'eshell-smart 'custom-loads '(em-smart))
(put 'rmail-summary 'custom-loads '(rmail rmailsum))
(put 'appt 'custom-loads '(appt))
(put 'iso-ascii 'custom-loads '(iso-ascii))
(put 'log-view 'custom-loads '(log-view))
(put 'vip 'custom-loads '(vip))
(put 'testcover 'custom-loads '(testcover))
(put 'gnus-article 'custom-loads '(gnus-art gnus-cite))
(put 'message-forwarding 'custom-loads '(message))
(put 'newsticker-ticker 'custom-loads '(newst-ticker))
(put 'gnus-group-icons 'custom-loads '(gnus-group))
(put 'ediff-diff 'custom-loads '(ediff-diff))
(put 'solitaire 'custom-loads '(solitaire))
(put 'reftex-miscellaneous-configurations 'custom-loads '(reftex-vars))
(put 'gnus 'custom-loads '(auth-source gnus gnus-art gnus-async gnus-bookmark gnus-delay gnus-demon gnus-diary gnus-dup gnus-eform gnus-uu deuglify gnus-sieve gnus-sync gnus-undo gnus-win mail-source mm-url nnir nnmail nnmairix nntp spam-stat))
(put 'gnus-registry 'custom-loads '(gnus-registry))
(put 'idlwave-external-programs 'custom-loads '(idlwave))
(put 'battery 'custom-loads '(battery))
(put 'iimage 'custom-loads '(iimage))
(put 'gnus-summary-maneuvering 'custom-loads '(gnus-sum))
(put 'calculator 'custom-loads '(calculator))
(put 'vhdl-misc 'custom-loads '(vhdl-mode))
(put 'org-export-icalendar 'custom-loads '(org-icalendar))
(put 'org-infojs 'custom-loads '(org-jsinfo))
(put 'canlock 'custom-loads '(canlock))
(put 'gnus-edit-form 'custom-loads '(gnus-eform))
(put 'vc-svn 'custom-loads '(vc-svn))
(put 'reftex-table-of-contents-browser 'custom-loads '(reftex-vars))
(put 'newsticker-reader 'custom-loads '(newst-reader newst-plainview newst-treeview))
(put 'ff 'custom-loads '(find-file))
(put 'ps-print-face 'custom-loads '(ps-print))
(put 'tools 'custom-loads '(calculator add-log compare-w compile copyright diff diff-mode ebrowse ede ediff elide-head emerge etags flymake gdb-mi glasses grep gud make-mode pcvs-defs "project-am" rcompile semantic sieve smerge-mode soap-client speedbar srecode tempo vc which-func))
(put 'eshell-arg 'custom-loads '(esh-arg))
(put 'gnus-group-various 'custom-loads '(gnus-group gnus-start gnus))
(put 'org-table-settings 'custom-loads '(org-table))
(put 'erc-autojoin 'custom-loads '(erc-join))
(put 'prolog-keyboard 'custom-loads '(prolog))
(put 'gdb-buffers 'custom-loads '(gdb-mi))
(put 'vc-sccs 'custom-loads '(vc-sccs))
(put 'tetris 'custom-loads '(tetris))
(put 'feedmail 'custom-loads '(feedmail))
(put 'editing-basics 'custom-loads '(cua-base))
(put 'org-edit-structure 'custom-loads '(org org-src))
(put 'org-agenda-search-view 'custom-loads '(org-agenda))
(put 'vc-hg 'custom-loads '(vc-hg))
(put 'nntp 'custom-loads '(nntp))
(put 'feedmail-queue 'custom-loads '(feedmail))
(put 'ediff-hook 'custom-loads '(ediff-init ediff-mult))
(put 'display-time 'custom-loads '(time))
(put 'org-publish 'custom-loads '(org-publish))
(put 'dig 'custom-loads '(dig net-utils))
(put 'semantic-modes 'custom-loads '("mru-bookmark"))
(put 'org-link-follow 'custom-loads '(org org-mhe))
(put 'frames 'custom-loads '(desktop ediff-wind imenu two-column))
(put 'org-beamer 'custom-loads '(org-beamer))
(put 'gnus-score-default 'custom-loads '(gnus-sum gnus-score))
(put 'vhdl-naming 'custom-loads '(vhdl-mode))
(put 'org-remember 'custom-loads '(org org-remember))
(put 'vhdl-speedbar 'custom-loads '(vhdl-mode))
(put 'gnus-summary-marks 'custom-loads '(gnus-sum gnus))
(put 'bs 'custom-loads '(bs))
(put 'rst-faces 'custom-loads '(rst))
(put 'vc-mtn 'custom-loads '(vc-mtn))
(put 'viper-ex 'custom-loads '(viper-ex))
(put 'eshell-proc 'custom-loads '(esh-proc))
(put 'erc-query 'custom-loads '(erc))
(put 'idlwave-shell-command-setup 'custom-loads '(idlw-shell))
(put 'isearch 'custom-loads '("misearch"))
(put 'expand 'custom-loads '(expand))
(put 'glasses 'custom-loads '(glasses))
(put 'erc-server-hooks 'custom-loads '(erc))
(put 'erc-hooks 'custom-loads '(erc erc-netsplit))
(put 'warnings 'custom-loads '(warnings))
(put 'python 'custom-loads '(python))
(put 'org-startup 'custom-loads '(org))
(put 'url 'custom-loads '(url-vars url url-cookie url-gw url-history url-irc url-news url-queue))
(put 'idlwave-routine-info 'custom-loads '(idlwave))
(put 'erc-display 'custom-loads '(erc erc-goodies))
(put 'highlight-changes 'custom-loads '(hilit-chg))
(put 'terminals 'custom-loads '(terminal))
(put 'gnus-sieve 'custom-loads '(gnus-sieve))
(put 'org-tags 'custom-loads '(org org-faces))
(put 'eshell-dirs 'custom-loads '(em-dirs))
(put 'shell 'custom-loads '(dirtrack shell terminal))
(put 'mairix 'custom-loads '(mairix))
(put 'mailcap 'custom-loads '(mailcap))
(put 'org-clocktable 'custom-loads '(org-clock))
(put 'mail 'custom-loads '(binhex time ecomplete emacsbug eudc-vars feedmail fortune gnus gnus-dired hashcash imap mail-utils mail-extr mail-hist mailalias mailclient mairix message metamail mm-decode mspools pop3 rmail sendmail shr sieve-manage smtpmail spam spam-report starttls supercite uce uudecode))
(put 'windows 'custom-loads '(follow windmove winner))
(put 'hi-lock-faces 'custom-loads '(hi-lock))
(put 'vcursor 'custom-loads '(vcursor))
(put 'org-export-translation 'custom-loads '(org-latex org-exp org))
(put 'find-function 'custom-loads '(find-func))
(put 'xesam 'custom-loads '(xesam))
(put 'c-macro 'custom-loads '(cmacexp))
(put 'edebug 'custom-loads '(edebug))
(put 'rmail-spam-filter 'custom-loads '(rmail-spam-filter))
(put 'org 'custom-loads '(org org-attach ob org-capture org-pcomplete org-crypt org-entities org-exp org-feed org-footnote org-freemind org-id org-indent org-mobile org-mouse org-protocol org-publish org-remember))
(put 'gnus-summary-mail 'custom-loads '(gnus-sum))
(put 'eshell-prompt 'custom-loads '(em-prompt))
(put 'files 'custom-loads '(ange-ftp autoinsert autorevert cus-edit dired filecache latexenc plstore recentf shadowfile tramp uniquify))
(put 'url-cache 'custom-loads '(url-vars url-cache))
(put 'url-hairy 'custom-loads '(url-vars url-util))
(put 'org-indent 'custom-loads '(org-indent))
(put 'fortune 'custom-loads '(fortune))
(put 'cua 'custom-loads '(cua-base))
(put 'org-agenda-windows 'custom-loads '(org-agenda org))
(put 'gnus-summary-format 'custom-loads '(gnus-diary gnus gnus-sum))
(put 'electric-help 'custom-loads '(ehelp))
(put 'dired-mark 'custom-loads '(dired))
(put 'languages 'custom-loads '(ps-mode sql ada-mode antlr-mode asm-mode cus-edit cfengine cperl-mode css-mode dcl-mode delphi f90 fortran hideshow icon idlwave info-look js ld-script m4-mode meta-mode modula2 nxml-mode octave-mod pascal perl-mode prolog python rng-valid ruby-mode sgml-mode sh-script sieve simula smie tcl vera-mode verilog-mode vhdl-mode))
(put 'gnus-group-listing 'custom-loads '(gnus-group))
(put 'gnutls 'custom-loads '(gnutls))
(put 'org-table-import-export 'custom-loads '(org-table))
(put 'css 'custom-loads '(css-mode))
(put 'minibuffer 'custom-loads '(icomplete savehist))
(put 'org-agenda-column-view 'custom-loads '(org-agenda))
(put 'comint 'custom-loads '(comint))
(put 'c 'custom-loads '("cc-vars" cc-fonts "cc-guess" cmacexp cpp hideif "c"))
(put 'fortune-signature 'custom-loads '(fortune))
(put 'supercite-frames 'custom-loads '(supercite))
(put 'widget-button 'custom-loads '(wid-edit))
(put 'gnus-format 'custom-loads '(gnus-spec))
(put 'prolog-other 'custom-loads '(prolog))
(put 'dcl 'custom-loads '(dcl-mode))
(put 'leim 'custom-loads '(quail))
(put 'PostScript-edit 'custom-loads '(ps-mode))
(put 'hide-ifdef 'custom-loads '(hideif))
(put 'find-file 'custom-loads '(find-file))
(put 'ebrowse-tree 'custom-loads '(ebrowse))
(put 'erc-identd 'custom-loads '(erc-identd))
(put 'tex-view 'custom-loads '(tex-mode))
(put 'columns 'custom-loads '(delim-col))
(put 'org-agenda-sorting 'custom-loads '(org-agenda))
(put 'sendmail 'custom-loads '(sendmail))
(put 'thumbs 'custom-loads '(thumbs))
(put 'org-agenda-startup 'custom-loads '(org-agenda))
(put 'gnus-dribble-file 'custom-loads '(gnus-start))
(put 'eshell-cmpl 'custom-loads '(em-cmpl))
(put 'gnus-article-mime 'custom-loads '(gnus-sum gnus-art mm-uu))
(put 'vhdl-testbench 'custom-loads '(vhdl-mode))
(put 'org-plain-lists 'custom-loads '(org-list))
(put 'erc-ezbounce 'custom-loads '(erc-ezbounce))
(put 'cpp 'custom-loads '(cpp))
(put 'ps-print-printer 'custom-loads '(lpr ps-print))
(put 'message-buffers 'custom-loads '(message))
(put 'xscheme 'custom-loads '(xscheme))
(put 'ebrowse 'custom-loads '(ebrowse))
(put 'org-export-pdf 'custom-loads '(org-latex))
(put 'custom-faces 'custom-loads '(cus-edit eieio-custom))
(put 'package 'custom-loads '(package-x package))
(put 'erc-autoaway 'custom-loads '(erc-autoaway))
(put 'ebnf-production 'custom-loads '(ebnf2ps))
(put 'gnus-score-expire 'custom-loads '(gnus-kill gnus-score))
(put 'longlines 'custom-loads '(longlines))
(put 'icomplete 'custom-loads '(icomplete))
(put 'erc-mode-line-and-header 'custom-loads '(erc))
(put 'vhdl-mode 'custom-loads '(vhdl-mode))
(put 'diff 'custom-loads '(diff diff-mode))
(put 'texinfo 'custom-loads '(informat "document" texinfo))
(put 'gnus-article-highlight 'custom-loads '(gnus-art))
(put 'nnmail-files 'custom-loads '(nnmail))
(put 'calc 'custom-loads '(calc))
(put 'nnir 'custom-loads '(nnir))
(put 'org-archive 'custom-loads '(org org-archive org-exp))
(put 'local 'custom-loads '(holidays))
(put 'docs 'custom-loads '(info makeinfo texinfo))
(put 'erc-log 'custom-loads '(erc-log))
(put 'auto-insert 'custom-loads '(autoinsert))
(put 'dired-faces 'custom-loads '(dired))
(put 'verilog-mode-indent 'custom-loads '(verilog-mode))
(put 'decipher 'custom-loads '(decipher))
(put 'eshell-pred 'custom-loads '(em-pred))
;; These are for handling :version.  We need to have a minimum of
;; information so `customize-changed-options' could do its job.

;; For groups we set `custom-version', `group-documentation' and
;; `custom-tag' (which are shown in the customize buffer), so we
;; don't have to load the file containing the group.

;; `custom-versions-load-alist' is an alist that has as car a version
;; number and as elts the files that have variables or faces that
;; contain that version. These files should be loaded before showing
;; the customization buffer that `customize-changed-options'
;; generates.

;; This macro is used so we don't modify the information about
;; variables and groups if it's already set. (We don't know when
;; cus-load.el is going to be loaded and at that time some of the
;; files might be loaded and some others might not).
(defmacro custom-put-if-not (symbol propname value)
  `(unless (get ,symbol ,propname)
     (put ,symbol ,propname ,value)))

(custom-put-if-not 'tildify 'custom-version "21.1")
(custom-put-if-not 'tildify 'group-documentation "Adding missing hard spaces or other text fragments into texts.")
(custom-put-if-not 'org-protocol 'custom-version "22.1")
(custom-put-if-not 'org-protocol 'group-documentation "Intercept calls from emacsclient to trigger custom actions.

This is done by advising `server-visit-files' to scan the list of filenames
for `org-protocol-the-protocol' and sub-protocols defined in
`org-protocol-protocol-alist' and `org-protocol-protocol-alist-default'.")
(custom-put-if-not 'vc-git 'custom-version "24.1")
(custom-put-if-not 'vc-git 'group-documentation "VC Git backend.")
(custom-put-if-not 'table 'custom-version "22.1")
(custom-put-if-not 'table 'group-documentation "Text based table manipulation utilities.")
(custom-put-if-not 'table 'custom-tag "Table")
(custom-put-if-not 'rst-faces-defaults 'custom-version "21.1")
(custom-put-if-not 'rst-faces-defaults 'group-documentation "Values used to generate default faces for section titles on all levels.
Tweak these if you are content with how section title faces are built in
general but you do not like the details.")
(custom-put-if-not 'spam-stat 'custom-version "22.1")
(custom-put-if-not 'spam-stat 'group-documentation "Statistical spam detection for Emacs.
Use the functions to build a dictionary of words and their statistical
distribution in spam and non-spam mails.  Then use a function to determine
whether a buffer contains spam or not.")
(custom-put-if-not 'SQL 'custom-version "20.4")
(custom-put-if-not 'SQL 'group-documentation "Running a SQL interpreter from within Emacs buffers.")
(custom-put-if-not 'ps-print-headers 'custom-version "20")
(custom-put-if-not 'ps-print-headers 'group-documentation "Headers & footers layout.")
(custom-put-if-not 'ps-print-headers 'custom-tag "Header & Footer")
(custom-put-if-not 'doc-view 'custom-version "22.2")
(custom-put-if-not 'doc-view 'group-documentation "In-buffer viewer for PDF, PostScript and DVI files.")
(custom-put-if-not 'whitespace 'custom-version "23.1")
(custom-put-if-not 'whitespace 'group-documentation "Visualize blanks (TAB, (HARD) SPACE and NEWLINE).")
(custom-put-if-not 'tree-widget 'custom-version "22.1")
(custom-put-if-not 'tree-widget 'group-documentation "Customization support for the Tree Widget library.")
(custom-put-if-not 'ido 'custom-version "22.1")
(custom-put-if-not 'ido 'group-documentation "Switch between files using substrings.")
(custom-put-if-not 'tramp 'custom-version "22.1")
(custom-put-if-not 'tramp 'group-documentation "Edit remote files with a combination of rsh and rcp or similar programs.")
(custom-put-if-not 'sieve 'custom-version "22.1")
(custom-put-if-not 'sieve 'group-documentation "Manage sieve scripts.")
(custom-put-if-not 'rcirc 'custom-version "22.1")
(custom-put-if-not 'rcirc 'group-documentation "Simple IRC client.")
(custom-put-if-not 'ps-print-horizontal 'custom-version "20")
(custom-put-if-not 'ps-print-horizontal 'group-documentation "Horizontal page layout.")
(custom-put-if-not 'ps-print-horizontal 'custom-tag "Horizontal")
(custom-put-if-not 'cperl 'custom-version "20.3")
(custom-put-if-not 'cperl 'group-documentation "Major mode for editing Perl code.")
(custom-put-if-not 'rst-adjust 'custom-version "21.1")
(custom-put-if-not 'rst-adjust 'group-documentation "Settings for adjustment and cycling of section title decorations.")
(custom-put-if-not 'ps-print-color 'custom-version "20")
(custom-put-if-not 'ps-print-color 'group-documentation "Color customization.")
(custom-put-if-not 'ps-print-color 'custom-tag "Color")
(custom-put-if-not 'vc-arch 'custom-version "24.1")
(custom-put-if-not 'vc-arch 'group-documentation "VC Arch backend.")
(custom-put-if-not 'ls-lisp 'custom-version "21.1")
(custom-put-if-not 'ls-lisp 'group-documentation "Emulate the ls program completely in Emacs Lisp.")
(custom-put-if-not 'org-export-odt 'custom-version "24.1")
(custom-put-if-not 'org-export-odt 'group-documentation "Options specific for ODT export of Org-mode files.")
(custom-put-if-not 'org-export-odt 'custom-tag "Org Export ODT")
(custom-put-if-not 'align 'custom-version "21.1")
(custom-put-if-not 'align 'group-documentation "Align text to a specific column, by regexp.")
(custom-put-if-not 'ps-print 'custom-version "20")
(custom-put-if-not 'ps-print 'group-documentation "PostScript generator for Emacs.")
(custom-put-if-not 'filesets 'custom-version "22.1")
(custom-put-if-not 'filesets 'group-documentation "The fileset swapper.")
(custom-put-if-not 'printing 'custom-version "22.1")
(custom-put-if-not 'printing 'group-documentation "Printing Utilities group.")
(custom-put-if-not 'printing 'custom-tag "Printing Utilities")
(custom-put-if-not 'nndiary 'custom-version "22.1")
(custom-put-if-not 'nndiary 'group-documentation "The Gnus Diary back end.")
(custom-put-if-not 'midnight 'custom-version "20.3")
(custom-put-if-not 'midnight 'group-documentation "Run something every day at midnight.")
(custom-put-if-not 'ebnf-displacement 'custom-version "20")
(custom-put-if-not 'ebnf-displacement 'group-documentation "Displacement customization.")
(custom-put-if-not 'ebnf-displacement 'custom-tag "Displacement")
(custom-put-if-not 'ldap 'custom-version "21.1")
(custom-put-if-not 'ldap 'group-documentation "Lightweight Directory Access Protocol.")
(custom-put-if-not 'gnus-diary 'custom-version "22.1")
(custom-put-if-not 'gnus-diary 'group-documentation "Utilities on top of the nndiary back end for Gnus.")
(custom-put-if-not 'ebnf-except 'custom-version "20")
(custom-put-if-not 'ebnf-except 'group-documentation "Except customization.")
(custom-put-if-not 'ebnf-except 'custom-tag "Except")
(custom-put-if-not 'gnus-sync 'custom-version "24.1")
(custom-put-if-not 'gnus-sync 'group-documentation "The Gnus synchronization facility.")
(custom-put-if-not 'gravatar 'custom-version "24.1")
(custom-put-if-not 'gravatar 'group-documentation "Gravatar.")
(custom-put-if-not 'ansi-colors 'custom-version "21.1")
(custom-put-if-not 'ansi-colors 'group-documentation "Translating SGR control sequences to faces.
This translation effectively colorizes strings and regions based upon
SGR control sequences embedded in the text.  SGR (Select Graphic
Rendition) control sequences are defined in section 3.8.117 of the
ECMA-48 standard (identical to ISO/IEC 6429), which is freely available
as a PDF file <URL:http://www.ecma.ch/ecma1/STAND/ECMA-048.HTM>.")
(custom-put-if-not 'postscript 'custom-version "20")
(custom-put-if-not 'postscript 'group-documentation "PostScript Group.")
(custom-put-if-not 'postscript 'custom-tag "PostScript")
(custom-put-if-not 'windmove 'custom-version "21.1")
(custom-put-if-not 'windmove 'group-documentation "Directional selection of windows in a frame.")
(custom-put-if-not 'vc-rcs 'custom-version "24.1")
(custom-put-if-not 'vc-rcs 'group-documentation "VC RCS backend.")
(custom-put-if-not 'starttls 'custom-version "21.1")
(custom-put-if-not 'starttls 'group-documentation "Support for `Transport Layer Security' protocol.")
(custom-put-if-not 'net-utils 'custom-version "20.3")
(custom-put-if-not 'net-utils 'group-documentation "Network utility functions.")
(custom-put-if-not 'emacs-lock 'custom-version "24.1")
(custom-put-if-not 'emacs-lock 'group-documentation "Emacs-Lock mode.")
(custom-put-if-not 'footnote 'custom-version "21.1")
(custom-put-if-not 'footnote 'group-documentation "Support for footnotes in mail and news messages.")
(custom-put-if-not 'ebnf-syntactic 'custom-version "20")
(custom-put-if-not 'ebnf-syntactic 'group-documentation "Syntactic customization.")
(custom-put-if-not 'ebnf-syntactic 'custom-tag "Syntactic")
(custom-put-if-not 'ps-print-background 'custom-version "20")
(custom-put-if-not 'ps-print-background 'group-documentation "Background customization.")
(custom-put-if-not 'ps-print-background 'custom-tag "Background")
(custom-put-if-not 'ebnf-optimization 'custom-version "20")
(custom-put-if-not 'ebnf-optimization 'group-documentation "Optimization customization.")
(custom-put-if-not 'ebnf-optimization 'custom-tag "Optimization")
(custom-put-if-not 'quickurl 'custom-version "21.1")
(custom-put-if-not 'quickurl 'group-documentation "Insert a URL based on text at point in buffer.")
(custom-put-if-not 'pcl-cvs 'custom-version "21.1")
(custom-put-if-not 'pcl-cvs 'group-documentation "Special support for the CVS versioning system.")
(custom-put-if-not 'elide-head 'custom-version "21.1")
(custom-put-if-not 'elide-head 'group-documentation "Eliding copyright headers and the like in source files.")
(custom-put-if-not 'eudc 'custom-version "21.1")
(custom-put-if-not 'eudc 'group-documentation "Emacs Unified Directory Client.")
(custom-put-if-not 'gnus-outlook-deuglify 'custom-version "22.1")
(custom-put-if-not 'gnus-outlook-deuglify 'group-documentation "Deuglify articles generated by broken user agents like MS Outlook (Express).")
(custom-put-if-not 'w32 'custom-version "22.1")
(custom-put-if-not 'w32 'group-documentation "MS-Windows specific features.")
(custom-put-if-not 'socks 'custom-version "22.2")
(custom-put-if-not 'socks 'group-documentation "SOCKS Support")
(custom-put-if-not 'recentf 'custom-version "21.1")
(custom-put-if-not 'recentf 'group-documentation "Maintain a menu of recently opened files.")
(custom-put-if-not 'gdb-non-stop 'custom-version "23.2")
(custom-put-if-not 'gdb-non-stop 'group-documentation "GDB non-stop debugging settings")
(custom-put-if-not 'delphi 'custom-version "21.1")
(custom-put-if-not 'delphi 'group-documentation "Major mode for editing Delphi source in Emacs.")
(custom-put-if-not 'gmm 'custom-version "22.1")
(custom-put-if-not 'gmm 'group-documentation "Utility functions for Gnus, Message and MML.")
(custom-put-if-not 'rst-toc 'custom-version "21.1")
(custom-put-if-not 'rst-toc 'group-documentation "Settings for reStructuredText table of contents.")
(custom-put-if-not 'ps-print-zebra 'custom-version "20")
(custom-put-if-not 'ps-print-zebra 'group-documentation "Zebra customization.")
(custom-put-if-not 'ps-print-zebra 'custom-tag "Zebra")
(custom-put-if-not 'shr 'custom-version "24.1")
(custom-put-if-not 'shr 'group-documentation "Simple HTML Renderer")
(custom-put-if-not 'ps-print-font 'custom-version "20")
(custom-put-if-not 'ps-print-font 'group-documentation "Fonts customization.")
(custom-put-if-not 'ps-print-font 'custom-tag "Font")
(custom-put-if-not 'gnus-delay 'custom-version "22.1")
(custom-put-if-not 'gnus-delay 'group-documentation "Arrange for sending postings later.")
(custom-put-if-not 'gametree 'custom-version "20.3")
(custom-put-if-not 'gametree 'group-documentation "Manage game analysis trees in Emacs.")
(custom-put-if-not 'verilog-mode 'custom-version "22.2")
(custom-put-if-not 'verilog-mode 'group-documentation "Facilitates easy editing of Verilog source text.")
(custom-put-if-not 'ses 'custom-version "21.1")
(custom-put-if-not 'ses 'group-documentation "Simple Emacs Spreadsheet.")
(custom-put-if-not 'rst 'custom-version "23.1")
(custom-put-if-not 'rst 'group-documentation "Support for reStructuredText documents.")
(custom-put-if-not 'snmp 'custom-version "20.4")
(custom-put-if-not 'snmp 'group-documentation "Mode for editing SNMP MIB files.")
(custom-put-if-not 'gdb 'custom-version "23.2")
(custom-put-if-not 'gdb 'group-documentation "GDB graphical interface")
(custom-put-if-not 'soap-client 'custom-version "24.1")
(custom-put-if-not 'soap-client 'group-documentation "Access SOAP web services from Emacs.")
(custom-put-if-not 'checkdoc 'custom-version "20.3")
(custom-put-if-not 'checkdoc 'group-documentation "Support for doc string checking in Emacs Lisp.")
(custom-put-if-not 'kmacro 'custom-version "22.1")
(custom-put-if-not 'kmacro 'group-documentation "Simplified keyboard macro user interface.")
(custom-put-if-not 'ebnf-special 'custom-version "20")
(custom-put-if-not 'ebnf-special 'group-documentation "Special customization.")
(custom-put-if-not 'ebnf-special 'custom-tag "Special")
(custom-put-if-not 'master 'custom-version "22.1")
(custom-put-if-not 'master 'group-documentation "Support for master/slave relationships between buffers.")
(custom-put-if-not 'paren-showing-faces 'custom-version "22.1")
(custom-put-if-not 'paren-showing-faces 'group-documentation "Group for faces of Show Paren mode.")
(custom-put-if-not 'savehist 'custom-version "22.1")
(custom-put-if-not 'savehist 'group-documentation "Save minibuffer history.")
(custom-put-if-not 'ps-print-vertical 'custom-version "20")
(custom-put-if-not 'ps-print-vertical 'group-documentation "Vertical page layout.")
(custom-put-if-not 'ps-print-vertical 'custom-tag "Vertical")
(custom-put-if-not 'ruler-mode 'custom-version "22.1")
(custom-put-if-not 'ruler-mode 'group-documentation "Display a ruler in the header line.")
(custom-put-if-not 'plstore 'custom-version "24.1")
(custom-put-if-not 'plstore 'group-documentation "Searchable, partially encrypted, persistent plist store")
(custom-put-if-not 'vc-cvs 'custom-version "24.1")
(custom-put-if-not 'vc-cvs 'group-documentation "VC CVS backend.")
(custom-put-if-not 'pcomplete 'custom-version "21.1")
(custom-put-if-not 'pcomplete 'group-documentation "Programmable completion.")
(custom-put-if-not 'ebnf-non-terminal 'custom-version "20")
(custom-put-if-not 'ebnf-non-terminal 'group-documentation "Non-Terminal customization.")
(custom-put-if-not 'ebnf-non-terminal 'custom-tag "Non-Terminal")
(custom-put-if-not 'ebnf2ps 'custom-version "20")
(custom-put-if-not 'ebnf2ps 'group-documentation "Translate an EBNF to a syntactic chart on PostScript.")
(custom-put-if-not 'conf 'custom-version "22.1")
(custom-put-if-not 'conf 'group-documentation "Configuration files.")
(custom-put-if-not 'flymake 'custom-version "23.1")
(custom-put-if-not 'flymake 'group-documentation "A universal on-the-fly syntax checker.")
(custom-put-if-not 'todo 'custom-version "21.1")
(custom-put-if-not 'todo 'group-documentation "Maintain a list of todo items.")
(custom-put-if-not 'comment 'custom-version "21.1")
(custom-put-if-not 'comment 'group-documentation "Indenting and filling of comments.")
(custom-put-if-not 'help-at-pt 'custom-version "22.1")
(custom-put-if-not 'help-at-pt 'group-documentation "Features for displaying local help.")
(custom-put-if-not 'epg 'custom-version "23.1")
(custom-put-if-not 'epg 'group-documentation "The EasyPG library.")
(custom-put-if-not 'epa 'custom-version "23.1")
(custom-put-if-not 'epa 'group-documentation "The EasyPG Assistant")
(custom-put-if-not 'mail-source 'custom-version "21.1")
(custom-put-if-not 'mail-source 'group-documentation "The mail-fetching library.")
(custom-put-if-not 'ebnf-shape 'custom-version "20")
(custom-put-if-not 'ebnf-shape 'group-documentation "Shapes customization.")
(custom-put-if-not 'ebnf-shape 'custom-tag "Shape")
(custom-put-if-not 'mime-display 'custom-version "21.1")
(custom-put-if-not 'mime-display 'group-documentation "Display of MIME in mail and news articles.")
(custom-put-if-not 'rst-compile 'custom-version "21.1")
(custom-put-if-not 'rst-compile 'group-documentation "Settings for support of conversion of reStructuredText
document with \\[rst-compile].")
(custom-put-if-not 'inferior-lisp 'custom-version "22.1")
(custom-put-if-not 'inferior-lisp 'group-documentation "Run an outside Lisp in an Emacs buffer.")
(custom-put-if-not 'vc-bzr 'custom-version "22.2")
(custom-put-if-not 'vc-bzr 'group-documentation "VC Bazaar (bzr) backend.")
(custom-put-if-not 'multi-isearch 'custom-version "23.1")
(custom-put-if-not 'multi-isearch 'group-documentation "Using isearch to search through multiple buffers.")
(custom-put-if-not 'ebnf-repeat 'custom-version "20")
(custom-put-if-not 'ebnf-repeat 'group-documentation "Repeat customization.")
(custom-put-if-not 'ebnf-repeat 'custom-tag "Repeat")
(custom-put-if-not 'ps-print-page 'custom-version "20")
(custom-put-if-not 'ps-print-page 'group-documentation "Page customization.")
(custom-put-if-not 'ps-print-page 'custom-tag "Page")
(custom-put-if-not 'gnus-charset 'custom-version "21.1")
(custom-put-if-not 'gnus-charset 'group-documentation "Group character set issues.")
(custom-put-if-not 'log-edit 'custom-version "21.1")
(custom-put-if-not 'log-edit 'group-documentation "Major mode for editing RCS and CVS commit messages.")
(custom-put-if-not 'ebnf-terminal 'custom-version "20")
(custom-put-if-not 'ebnf-terminal 'group-documentation "Terminal customization.")
(custom-put-if-not 'ebnf-terminal 'custom-tag "Terminal")
(custom-put-if-not 'ibuffer 'custom-version "22.1")
(custom-put-if-not 'ibuffer 'group-documentation "An advanced replacement for `buffer-menu'.

Ibuffer allows you to operate on buffers in a manner much like Dired.
Operations include sorting, marking by regular expression, and
the ability to filter the displayed buffers by various criteria.")
(custom-put-if-not 'generic-x 'custom-version "20.3")
(custom-put-if-not 'generic-x 'group-documentation "A collection of generic modes.")
(custom-put-if-not 'vera 'custom-version "22.2")
(custom-put-if-not 'vera 'group-documentation "Customizations for Vera Mode.")
(custom-put-if-not 'diff-mode 'custom-version "21.1")
(custom-put-if-not 'diff-mode 'group-documentation "Major mode for viewing/editing diffs.")
(custom-put-if-not 'ps-print-miscellany 'custom-version "20")
(custom-put-if-not 'ps-print-miscellany 'group-documentation "Miscellany customization.")
(custom-put-if-not 'ps-print-miscellany 'custom-tag "Miscellany")
(custom-put-if-not 'auth-source 'custom-version "23.1")
(custom-put-if-not 'auth-source 'group-documentation "Authentication sources.")
(custom-put-if-not 'eshell 'custom-version "21.1")
(custom-put-if-not 'eshell 'group-documentation "A command shell implemented entirely in Emacs Lisp.
It invokes no external processes beyond those requested by the
user, and is intended to be a functional replacement for command
shells such as bash, zsh, rc, 4dos.")
(custom-put-if-not 'eshell 'custom-tag "The Emacs shell")
(custom-put-if-not 'ps-print-n-up 'custom-version "20")
(custom-put-if-not 'ps-print-n-up 'group-documentation "N-up customization.")
(custom-put-if-not 'ps-print-n-up 'custom-tag "N-Up")
(custom-put-if-not 'imap 'custom-version "21.1")
(custom-put-if-not 'imap 'group-documentation "Low-level IMAP issues.")
(custom-put-if-not 'epa-faces 'custom-version "23.1")
(custom-put-if-not 'epa-faces 'group-documentation "Faces for epa-mode.")
(custom-put-if-not 'cwarn 'custom-version "21.1")
(custom-put-if-not 'cwarn 'group-documentation "Highlight suspicious C and C++ constructions.")
(custom-put-if-not 'testcover 'custom-version "21.1")
(custom-put-if-not 'testcover 'group-documentation "Code-coverage tester.")
(custom-put-if-not 'gnus-registry 'custom-version "22.1")
(custom-put-if-not 'gnus-registry 'group-documentation "Article Registry.")
(custom-put-if-not 'iimage 'custom-version "22.1")
(custom-put-if-not 'iimage 'group-documentation "Support for inline images.")
(custom-put-if-not 'calculator 'custom-version "21.1")
(custom-put-if-not 'calculator 'group-documentation "Simple Emacs calculator.")
(custom-put-if-not 'vc-svn 'custom-version "24.1")
(custom-put-if-not 'vc-svn 'group-documentation "VC Subversion (svn) backend.")
(custom-put-if-not 'ps-print-face 'custom-version "20")
(custom-put-if-not 'ps-print-face 'group-documentation "Faces customization.")
(custom-put-if-not 'ps-print-face 'custom-tag "PS Faces")
(custom-put-if-not 'gdb-buffers 'custom-version "23.2")
(custom-put-if-not 'gdb-buffers 'group-documentation "GDB buffers")
(custom-put-if-not 'vc-sccs 'custom-version "24.1")
(custom-put-if-not 'vc-sccs 'group-documentation "VC SCCS backend.")
(custom-put-if-not 'vc-hg 'custom-version "24.1")
(custom-put-if-not 'vc-hg 'group-documentation "VC Mercurial (hg) backend.")
(custom-put-if-not 'bs 'custom-version "21.1")
(custom-put-if-not 'bs 'group-documentation "Buffer Selection: Maintaining buffers by buffer menu.")
(custom-put-if-not 'rst-faces 'custom-version "21.1")
(custom-put-if-not 'rst-faces 'group-documentation "Faces used in Rst Mode.")
(custom-put-if-not 'vc-mtn 'custom-version "24.1")
(custom-put-if-not 'vc-mtn 'group-documentation "VC Monotone (mtn) backend.")
(custom-put-if-not 'glasses 'custom-version "21.1")
(custom-put-if-not 'glasses 'group-documentation "Make unreadable code likeThis(one) readable.")
(custom-put-if-not 'warnings 'custom-version "22.1")
(custom-put-if-not 'warnings 'group-documentation "Log and display warnings.")
(custom-put-if-not 'python 'custom-version "22.1")
(custom-put-if-not 'python 'group-documentation "Silly walks in the Python language.")
(custom-put-if-not 'url 'custom-version "22.1")
(custom-put-if-not 'url 'group-documentation "Uniform Resource Locator tool.")
(custom-put-if-not 'mailcap 'custom-version "21.1")
(custom-put-if-not 'mailcap 'group-documentation "Definition of viewers for MIME types.")
(custom-put-if-not 'xesam 'custom-version "23.1")
(custom-put-if-not 'xesam 'group-documentation "Xesam compatible interface to search engines.")
(custom-put-if-not 'fortune 'custom-version "21.1")
(custom-put-if-not 'fortune 'group-documentation "Settings for fortune.")
(custom-put-if-not 'cua 'custom-version "22.1")
(custom-put-if-not 'cua 'group-documentation "Emulate CUA key bindings including C-x and C-c.")
(custom-put-if-not 'electric-help 'custom-version "21.1")
(custom-put-if-not 'electric-help 'group-documentation "Electric help facility.")
(custom-put-if-not 'gnutls 'custom-version "24.1")
(custom-put-if-not 'gnutls 'group-documentation "Emacs interface to the GnuTLS library.")
(custom-put-if-not 'thumbs 'custom-version "22.1")
(custom-put-if-not 'thumbs 'group-documentation "Thumbnails previewer.")
(custom-put-if-not 'ps-print-printer 'custom-version "20")
(custom-put-if-not 'ps-print-printer 'group-documentation "Printer customization.")
(custom-put-if-not 'ps-print-printer 'custom-tag "Printer")
(custom-put-if-not 'package 'custom-version "24.1")
(custom-put-if-not 'package 'group-documentation "Manager for Emacs Lisp packages.")
(custom-put-if-not 'ebnf-production 'custom-version "20")
(custom-put-if-not 'ebnf-production 'group-documentation "Production customization.")
(custom-put-if-not 'ebnf-production 'custom-tag "Production")

(defvar custom-versions-load-alist '(("20.3.3" "dos-vars") ("21.2" mm-util) ("20.4" hilit-chg crisp sh-script compile) ("19.29" time-stamp) ("23.4" ede) ("20.8" sql) ("21.3" sql gnus-agent ange-ftp) ("22" ps-print ebnf2ps) ("22.3" message) ("20.1" time-stamp) ("20.3" xscheme etags browse-url dabbrev sendmail vcursor uce msb compile hexl which-func avoid find-func paren add-log debug ffap rmail cus-edit diary-lib vc) ("23.3" diary-lib rmail python desktop rmailsum calendar) ("20" ebnf2ps ps-print) ("23.2" bytecomp comint rmailmm rmail diary-lib desktop lunar mm-encode elint doc-view gnus-sum calendar gnus-group help-fns dired ansi-color tramp-gvfs auth-source message gdb-mi) ("22.2" gnus-sum bibtex-style mail-source sql dired gdb-mi find-dired tls desktop css-mode vc-mtn vc-hg) ("21.1" strokes dabbrev ezimage sgml-mode cal-hebrew sendmail ange-ftp gnus-group gnus-start vc-cvs debug vc-rcs net-utils vc-sccs smtpmail vc server browse-url message paren wid-edit fortran rmailedit find-func ps-print hideshow sb-image gnus-sum rmail cperl-mode latin1-disp gnus-art gnus-agent nnmail add-log flyspell etags cus-edit) ("22.1" uudecode calendar comint dabbrev add-log tcl latin1-disp imap gnus-delay mml2015 ange-ftp gnus-srvr hi-lock view mail-source descr-text fortran allout ielm smime mail-extr rmail gnus-util shadowfile cal-dst gnus-score hl-line sh-script bookmark glasses cus-edit gnus-int locate diary-lib ispell vc-svn gnus-msg landmark diff-mode mm-view cal-tex gnus-start gnus-fun vc-cvs find-func gnus-cite starttls flow-fill mm-uu make-mode generic-x info deuglify keypad sendmail spam desktop mm-url sql autorevert pop3 gnus-spec ffap grep mml gnus time sgml-mode gnus-win mml-sec tex-mode iswitchb gnus-art compile imenu warnings dired gdb-mi server vc gnus-sum tls binhex gnus-group mm-decode message compare-w nnmail mm-util gnus-agent) ("23.1" f90 gnus-dired informat smiley gnus-msg fortran bibtex vc-cvs mml spam-report rmailmm woman server "misearch" vc-git gnus-util vc-mtn hideif info ffap allout smime filesets gnus-score gnus copyright dired-aux fortune browse-url nnmail icomplete compile vc-hg cus-edit checkdoc vc-arch view gnus-bookmark newcomment tex-mode rmail mm-uu gdb-mi face-remap sendmail net-utils nnmairix pcmpl-unix gnus-draft tls calendar time holidays pop3 gnus-art descr-text gnus-sum imap mm-decode gnus-group message) ("24.1" ob-exp em-smart ob-lisp vc-sccs mm-view gnus-msg cc-fonts server org-gnus org-src esh-ext shr em-rebind rmail esh-mode url-cache org-archive org-freemind pcmpl-unix vc-svn em-unix gnus-srvr vc-bzr org-docbook woman dirtrack smiley esh-io em-cmpl copyright em-ls tramp org-exp-blocks ob-lob js esh-var saveplace em-dirs image-mode em-script vc-git gnus-registry flyspell calendar doc-view org-faces em-pred mm-decode netrc mml2015 ob-plantuml gssapi org-attach mml electric vc-hg gnus log-edit package-x diary-lib gnus-group pop3 cus-edit gnus-art dired-x auth-source org-ctags org-habit "cl-indent" url-queue browse-url hl-line org-publish em-hist compile esh-proc esh-arg battery org-capture org-clock gnus-int ange-ftp vc gnus-gravatar org-timer erc-backend ob-picolisp em-term ido gnus-async gnus-util ob-js comint gnus-start allout feedmail "cc-guess" etags org-taskjuggler cus-theme verilog-mode appt esh-cmd emacs-lock org-inlinetask em-prompt org-wl em-banner glasses org-table esh-util org-html gnus-picon org-beamer org-mobile arc-mode em-glob vc-cvs man ibuffer org-list allout-widgets erc-join ob-scheme org-exp "cc-vars" ob-tangle gnus-html python org-agenda ses calc smtpmail ob sendmail find-dired org-entities sql org-icalendar message em-alias org nnir package bibtex rcirc org-bibtex gnus-sum org-latex vc-rcs sieve-manage org-odt info rst f90 prolog))
 "For internal use by custom.")

(provide 'cus-load)
;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8
;; End:
;;; cus-load.el ends here
