<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array/>
	<key>injectionSelector</key>
	<string>source.c++ - string - comment, source.objc++ - string - comment</string>
	<key>name</key>
	<string>OakDebug</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\b([rc]?iterate)\b</string>
			<key>name</key>
			<string>keyword.control.$1.oak.c++</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(DBF_(\w+))\b</string>
			<key>name</key>
			<string>constant.other.variable.oak-debug.${2:/downcase}.c++</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.c++.oak-debug</string>
	<key>uuid</key>
	<string>B6359B60-304A-4607-AA80-CFB55E337EF6</string>
</dict>
</plist>
