(nxml-define-char-name-set 'currency-symbols
  '(("EURO-CURRENCY SIGN" #x20A0)
    ("COLON SIGN" #x20A1)
    ("CRUZEIRO SIGN" #x20A2)
    ("FRENCH FRANC SIGN" #x20A3)
    ("LIRA SIGN" #x20A4)
    ("MILL SIGN" #x20A5)
    ("NAIRA SIGN" #x20A6)
    ("PESETA SIGN" #x20A7)
    ("RUPEE SIGN" #x20A8)
    ("WON SIGN" #x20A9)
    ("NEW SHEQEL SIGN" #x20AA)
    ("DONG SIGN" #x20AB)
    ("EURO SIGN" #x20AC)
    ("KIP SIGN" #x20AD)
    ("TUGRIK SIGN" #x20AE)
    ("DRACHMA SIGN" #x20AF)
    ("GERMAN PENNY SIGN" #x20B0)
    ("PESO SIGN" #x20B1)
    ))

