(nxml-define-char-name-set 'combining-half-marks
  '(("COMBINING LIGATURE LEFT HALF" #xFE20)
    ("COMBINING LIGATURE RIGHT HALF" #xFE21)
    ("COMBINING DOUBLE TILDE LEFT HALF" #xFE22)
    ("COMBINING DOUBLE TILDE RIGHT HALF" #xFE23)
    ))

