(nxml-define-char-name-set 'specials
  '(("INTERLINEAR ANNOTATION ANCHOR" #xFFF9)
    ("INTERLINEAR ANNOTATION SEPARATOR" #xFFFA)
    ("INTERLINEAR ANNOTATION TERMINATOR" #xFFFB)
    ("OBJECT REPLACEMENT CHARACTER" #xFFFC)
    ("REPLACEMENT CHARACTER" #xFFFD)
    ))

