@c -*-texinfo-*-
@setfilename ../../info/index

@c Indexing guidelines

@c I assume that all indexes will be combined.
@c Therefore, if a generated findex and permutations
@c cover the ways an index user would look up the entry,
@c then no cindex is added.
@c Concept index (cindex) entries will also be permuted.  Therefore, they
@c have no commas and few irrelevant connectives in them.

@c I tried to include words in a cindex that give the context of the entry,
@c particularly if there is more than one entry for the same concept.
@c For example, "nil in keymap"
@c Similarly for explicit findex and vindex entries, e.g. "print example".

@c Error codes are given cindex entries, e.g. "end-of-file error".

@c pindex is used for .el files and Unix programs

@node Index, , Standard Hooks, Top
@unnumbered Index

@c Print the indices

@printindex fn


